import type { Metadata } from "next";

import "./globals.css";
import { Footer } from "@/components/footer";
import { ClerkProvider } from "@clerk/nextjs";
import { ModalProvider } from "@/components/modal-provider";

import { Toaster } from "@/components/ui/sonner";
import { Navbar } from "@/components/nav";


export const metadata: Metadata = {
  title: "Code X",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`antialiased`}
        >
          
            <ModalProvider />
            <Navbar />
            {children}
            <Footer />
            <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
